// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function ClearHistory():Promise<void>;

export function CopyToClipboard(arg1:services.ClipboardItem):Promise<void>;

export function DeleteItem(arg1:string):Promise<void>;

export function GetHistory():Promise<Array<services.ClipboardItem>>;

export function GetImageData(arg1:string):Promise<string>;

export function Quit():Promise<void>;
